name: 'Build KIND'
description: 'Build KIND application using PyInstaller'
runs:
  using: "composite"
  steps:
    - name: Build with PyInstaller (Windows)
      if: runner.os == 'Windows'
      run: |
        pyinstaller --name=KIND --windowed --onefile main.py
      shell: pwsh
    - name: Build with PyInstaller (macOS)
      if: runner.os == 'macOS'
      run: |
        pyinstaller --name=KIND --windowed --onefile main.py
        mv dist/KIND dist/KIND.app
      shell: bash