name: Build KIND

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyQt6 pyinstaller
      - name: Build with PyInstaller
        run: pyinstaller --distpath dist/kind --onefile main.py
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kind-${{ matrix.os }}
          path: dist/kind

  release:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Zip artifacts
        run: |
          if [ -d "kind-${{ matrix.os }}" ]; then
            zip -r "kind-${{ matrix.os }}.zip" "kind-${{ matrix.os }}"
          else
            echo "Directory kind-${{ matrix.os }} not found, skipping..."
          fi
      - name: Upload Release Assets (using latest version, with error handling)
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/kind-windows-latest.zip
          asset_name: kind-windows-latest.zip
          asset_content_type: application/zip
      - name: Upload Release Assets (MacOS) (using latest version, with error handling)
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/kind-macos-latest.zip
          asset_name: kind-macos-latest.zip
          asset_content_type: application/zip
