name: Build Cat Pet Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt6 pyinstaller

    - name: Build with PyInstaller
      run: pyinstaller cat_pet.spec

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: CatPet-${{ matrix.os }}
        path: dist/CatPet

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v3

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Download artifacts
      uses: actions/download-artifact@v3

    - name: Zip artifacts
      run: |
        zip -r CatPet-Windows.zip CatPet-windows-latest
        zip -r CatPet-MacOS.zip CatPet-macos-latest
        zip -r CatPet-Ubuntu.zip CatPet-ubuntu-latest

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./CatPet-Windows.zip
        asset_name: CatPet-Windows.zip
        asset_content_type: application/zip

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./CatPet-MacOS.zip
        asset_name: CatPet-MacOS.zip
        asset_content_type: application/zip

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./CatPet-Ubuntu.zip
        asset_name: CatPet-Ubuntu.zip
        asset_content_type: application/zip
