name: Build Cat Pet Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
      fail-fast: false  # This allows other builds to continue if one fails

    steps:
      - uses: actions/checkout@v4  # Updated to v4

      - name: Set up Python
        uses: actions/setup-python@v5  # Updated to v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyQt6 pyinstaller

      - name: Build with PyInstaller
        run: pyinstaller --distpath dist/CatPet --onefile main.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: CatPet-${{ matrix.os }}
          path: dist/CatPet

  release:
    needs: build
    runs-on: [windows-latest, macos-latest]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4  # Updated to v4

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest 
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Download artifacts
        uses: actions/download-artifact@v4 

      - name: Zip artifacts
        run: |
          for os in windows-latest macos-latest; do  # Only consider Windows and macOS
            if [ -d "CatPet-$os" ]; then
              zip -r "CatPet-$(echo $os | cut -d'-' -f1 | tr '[:lower:]' '[:upper:]').zip" "CatPet-$os"
            else
              echo "Directory CatPet-$os not found, skipping..."
            fi
          done

      - name: Upload Release Assets (using latest version, with error handling)
        uses: actions/upload-release-asset@latest  # Update to latest version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/CatPet-Windows.zip
          asset_name: CatPet-Windows.zip
          asset_content_type: application/zip

      - name: Upload Release Assets (MacOS) (using latest version, with error handling)
        uses: actions/upload-release-asset@latest  # Update to latest version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/CatPet-MacOS.zip
          asset_name: CatPet-MacOS.zip
          asset_content_type: application/zip
