name: Build and Release KIND

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: pip install PyQt6 pyinstaller
      - name: Build with PyInstaller
        run: pyinstaller --name=KIND --windowed --add-data "assets:assets" main.py
        shell: bash
      - name: Zip artifacts
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            powershell Compress-Archive -Path dist\KIND\* -DestinationPath KIND-Windows.zip
          else
            cd dist && zip -r ../KIND-${{ runner.os }}.zip KIND*
          fi
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: KIND-${{ runner.os }}
          path: KIND-${{ runner.os }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v${{ github.run_number }} \
            --title "Release ${{ github.run_number }}" \
            --generate-notes
      - uses: actions/download-artifact@v4
      - name: Upload Release Assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for zip in KIND-*.zip; do
            gh release upload v${{ github.run_number }} $zip
          done